### ISSUE TITLE
Please rename shared-common-API to "foundations API", to avoid confusion

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/foundation-API#7] opened 2020-11-23 09:29 UTC

**Comment by leosobral** [comment] 2020-11-23 15:20
This is a duplicate of https://github.com/buildingSMART/shared-common-API/issues/9 :-)

**Comment by ykulbak** [comment] 2020-11-24 09:39
In the Open cde hackathon it was decided to:
1. Rename to `opencde-foundation-API`
2. Change all `open-cde` and `open cde` references to `opencde`

**Closed as completed** 2020-11-25 05:03 UTC
